import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms' | 'liability' | 'about';
}

export function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
  const content = {
    about: {
      title: "About TripIntel",
      body: `
        <p>TripIntel.net is a <strong>Global Mobility Hub</strong>, providing data-driven information and insights for anyone moving across borders, whether for a week of sightseeing or a permanent move for work and family.</p>
        
        <p class="mt-4">As a cutting-edge real-time intelligence platform designed for the modern global citizen, we provide unfiltered, data-driven insights into travel, education, and business markets worldwide.</p>
        
        <h4 class="font-black uppercase mt-6 text-[#ff5757]">Our Core Mission</h4>
        <p>In an era of curated social media and biased reviews, TripIntel delivers the blunt truth. Our systems analyze thousands of live data points to give you the real story before you commit your time or capital.</p>

        <h4 class="font-black uppercase mt-6 text-[#5ce1e6]">New: Global School Intelligence</h4>
        <p>We've launched a first-of-its-kind real-time school quality checker. From curriculum depth to teacher-to-student ratios and infrastructure health, we provide a transparent look at educational institutions across the globe, updated as changes happen.</p>

        <h4 class="font-black uppercase mt-6 text-[#ffde59]">New: Business Investment Tracker</h4>
        <p>Navigate global markets with our real-time business intelligence suite. We track commercial registration hurdles, local ownership requirements, and market volatility in real-time for any city in the world, helping founders and investors make informed decisions in emerging and established hubs.</p>

        <p class="mt-6 font-black uppercase tracking-widest text-sm border-t-2 border-black pt-4">Powered by Real-Time Data Streams & Advanced Intelligence.</p>
      `
    },
    privacy: {
      title: "Privacy Policy",
      body: `
        <p>At TripIntel, we take your privacy seriously. This policy outlines how we handle your data.</p>
        <h4 class="font-black uppercase mt-4">1. Data Collection</h4>
        <p>We do not store personal identification information. We only process the destination and month you search for to provide travel advice via the safetyindex.net API.</p>
        <h4 class="font-black uppercase mt-4">2. Third-Party Services</h4>
        <p>We use safetyindex.net API to generate travel snapshots. Your search queries are sent to safetyindex.net to facilitate this service.</p>
        <h4 class="font-black uppercase mt-4">3. Cookies</h4>
        <p>We may use local storage to remember your preferences, but we do not use tracking cookies for advertising.</p>
      `
    },
    terms: {
      title: "Terms of Service",
      body: `
        <p>By using TripIntel, you agree to the following terms.</p>
        <h4 class="font-black uppercase mt-4">1. Usage</h4>
        <p>This tool is for informational purposes only. You agree not to use this service for any illegal activities.</p>
        <h4 class="font-black uppercase mt-4">2. Intellectual Property</h4>
        <p>The design and code of TripIntel are protected by copyright. The travel advice generated is provided "as-is".</p>
      `
    },
    liability: {
      title: "Legal Liability Disclaimer",
      body: `
        <p class="text-red-600 font-black uppercase mb-4">Read carefully: This is a legal disclaimer.</p>
        <h4 class="font-black uppercase mt-4">1. AI-Generated Content</h4>
        <p>All travel advice, scores, and snapshots provided by TripIntel are generated by Artificial Intelligence (safetyindex.net). AI can make mistakes, hallucinate facts, or provide outdated information.</p>
        <h4 class="font-black uppercase mt-4">2. No Guarantee of Accuracy</h4>
        <p>TripIntel and its creators do not guarantee the accuracy, completeness, or reliability of any information provided. Weather patterns, local laws, safety conditions, and pricing can change rapidly.</p>
        <h4 class="font-black uppercase mt-4">3. User Responsibility</h4>
        <p>You are solely responsible for verifying all information (including visas, safety warnings, and health requirements) with official government sources and local authorities before booking or embarking on travel.</p>
        <h4 class="font-black uppercase mt-4">4. Limitation of Liability</h4>
        <p>In no event shall TripIntel, its developers, or safetyindex.net be liable for any direct, indirect, incidental, or consequential damages arising out of your use of the information provided by this service.</p>
      `
    }
  };

  const activeContent = content[type];

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />
          <motion.div 
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            className="relative w-full max-w-2xl bg-white brutal-border p-8 overflow-y-auto max-h-[90vh]"
          >
            <button 
              onClick={onClose}
              className="absolute top-4 right-4 p-2 hover:bg-gray-100 rounded-full transition-colors"
            >
              <X className="w-6 h-6" />
            </button>
            
            <h2 className="text-3xl font-black uppercase tracking-tighter mb-6 border-b-4 border-black pb-2">
              {activeContent.title}
            </h2>
            
            <div 
              className="prose prose-slate max-w-none font-bold text-gray-800 space-y-4"
              dangerouslySetInnerHTML={{ __html: activeContent.body }}
            />
            
            <div className="mt-8 flex justify-end">
              <button 
                onClick={onClose}
                className="brutal-btn bg-[#ffde59] px-8 py-2 font-black uppercase tracking-widest"
              >
                Understood
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
