export const DESTINATIONS = [
  "Tokyo, Japan",
  "Paris, France",
  "London, UK",
  "Bangkok, Thailand",
  "Dubai, UAE",
  "New York City, USA",
  "Rome, Italy",
  "Istanbul, Turkey",
  "Cairo, Egypt",
  "Mumbai, India",
  "Bali, Indonesia",
  "Sydney, Australia",
  "Barcelona, Spain",
  "Toronto, Canada",
  "Mexico City, Mexico",
  "Cape Town, South Africa",
  "Maldives",
  "Santorini, Greece",
  "Cancun, Mexico",
  "Melbourne, Australia",
  "Miami, USA",
  "Amsterdam, Netherlands",
  "Seoul, South Korea",
  "Singapore",
  "Hong Kong",
  "Prague, Czech Republic",
  "Vienna, Austria",
  "Berlin, Germany",
  "Madrid, Spain",
  "Lisbon, Portugal",
  "Venice, Italy",
  "Florence, Italy",
  "Marrakesh, Morocco",
  "Kyoto, Japan",
  "Osaka, Japan",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Machu Picchu, Peru",
  "Petra, Jordan",
  "Athens, Greece",
  "Dublin, Ireland",
  "Edinburgh, Scotland",
  "Reykjavik, Iceland",
  "Vancouver, Canada",
  "San Francisco, USA",
  "Los Angeles, USA",
  "Las Vegas, USA",
  "New Orleans, USA",
  "Chicago, USA",
  "Seattle, USA",
  "Montreal, Canada",
  "Quebec City, Canada",
  "Munich, Germany",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Krakow, Poland",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Nice, France",
  "Lyon, France",
  "Bordeaux, France",
  "Seville, Spain",
  "Valencia, Spain",
  "Granada, Spain",
  "Porto, Portugal",
  "Milan, Italy",
  "Naples, Italy",
  "Verona, Italy",
  "Amalfi Coast, Italy",
  "Mykonos, Greece",
  "Crete, Greece",
  "Rhodes, Greece",
  "Phuket, Thailand",
  "Koh Samui, Thailand",
  "Chiang Mai, Thailand",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Hoi An, Vietnam",
  "Siem Reap, Cambodia",
  "Luang Prabang, Laos",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Langkawi, Malaysia",
  "Boracay, Philippines",
  "El Nido, Philippines",
  "Cebu, Philippines",
  "Taipei, Taiwan",
  "Shanghai, China",
  "Beijing, China",
  "Xi'an, China",
  "Chengdu, China",
  "Guilin, China",
  "Kathmandu, Nepal",
  "Pokhara, Nepal",
  "New Delhi, India",
  "Jaipur, India",
  "Agra, India",
  "Varanasi, India",
  "Goa, India",
  "Colombo, Sri Lanka",
  "Kandy, Sri Lanka",
  "Male, Maldives",
  "Bora Bora, French Polynesia",
  "Moorea, French Polynesia",
  "Fiji",
  "Auckland, New Zealand",
  "Queenstown, New Zealand",
  "Christchurch, New Zealand",
  "Gold Coast, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Cairns, Australia",
  "Ayers Rock, Australia",
  "Honolulu, USA",
  "Maui, USA",
  "Kauai, USA",
  "Big Island, USA",
  "Anchorage, USA",
  "Fairbanks, USA",
  "Juneau, USA",
  "San Juan, Puerto Rico",
  "Havana, Cuba",
  "Nassau, Bahamas",
  "Montego Bay, Jamaica",
  "Punta Cana, Dominican Republic",
  "Grand Cayman, Cayman Islands",
  "St. Barts",
  "St. Lucia",
  "Barbados",
  "Antigua",
  "Grenada",
  "Aruba",
  "Curacao",
  "Bonaire",
  "Turks and Caicos",
  "Bermuda",
  "Galapagos Islands, Ecuador",
  "Quito, Ecuador",
  "Lima, Peru",
  "Cusco, Peru",
  "Santiago, Chile",
  "Easter Island, Chile",
  "Patagonia, Chile/Argentina",
  "Iguazu Falls, Argentina/Brazil",
  "Sao Paulo, Brazil",
  "Salvador, Brazil",
  "Cartagena, Colombia",
  "Bogota, Colombia",
  "Medellin, Colombia",
  "Panama City, Panama",
  "San Jose, Costa Rica",
  "La Fortuna, Costa Rica",
  "Manuel Antonio, Costa Rica",
  "Belize City, Belize",
  "Antigua, Guatemala",
  "Roatan, Honduras",
  "San Salvador, El Salvador",
  "Managua, Nicaragua",
  "Casablanca, Morocco",
  "Fes, Morocco",
  "Chefchaouen, Morocco",
  "Tunis, Tunisia",
  "Luxor, Egypt",
  "Aswan, Egypt",
  "Sharm El Sheikh, Egypt",
  "Hurghada, Egypt",
  "Nairobi, Kenya",
  "Mombasa, Kenya",
  "Maasai Mara, Kenya",
  "Serengeti, Tanzania",
  "Zanzibar, Tanzania",
  "Mount Kilimanjaro, Tanzania",
  "Victoria Falls, Zambia/Zimbabwe",
  "Johannesburg, South Africa",
  "Kruger National Park, South Africa",
  "Durban, South Africa",
  "Windhoek, Namibia",
  "Etosha National Park, Namibia",
  "Sossusvlei, Namibia",
  "Antananarivo, Madagascar",
  "Nosy Be, Madagascar",
  "Mauritius",
  "Seychelles",
  "Reunion Island",
  "Muscat, Oman",
  "Salalah, Oman",
  "Doha, Qatar",
  "Abu Dhabi, UAE",
  "Manama, Bahrain",
  "Kuwait City, Kuwait",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Al Ula, Saudi Arabia",
  "Jerusalem, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Wadi Rum, Jordan",
  "Dead Sea, Jordan",
  "Tbilisi, Georgia",
  "Yerevan, Armenia",
  "Baku, Azerbaijan",
  "Tashkent, Uzbekistan",
  "Samarkand, Uzbekistan",
  "Bukhara, Uzbekistan",
  "Almaty, Kazakhstan",
  "Astana, Kazakhstan",
  "Ulaanbaatar, Mongolia",
  "Ankara, Turkey",
  "Baghdad, Iraq",
  "Kabul, Afghanistan",
  "Moscow, Russia",
  "Brussels, Belgium",
  "Bruges, Belgium",
  "Antwerp, Belgium",
  "Rotterdam, Netherlands",
  "Luxembourg City, Luxembourg",
  "Strasbourg, France",
  "Marseille, France",
  "Toulouse, France",
  "Nantes, France",
  "Lille, France",
  "Montpellier, France",
  "Cannes, France",
  "Monaco",
  "Basel, Switzerland",
  "Bern, Switzerland",
  "Salzburg, Austria",
  "Innsbruck, Austria",
  "Graz, Austria",
  "Vaduz, Liechtenstein",
  "San Marino",
  "Vatican City",
  "Valletta, Malta",
  "Nicosia, Cyprus",
  "Limassol, Cyprus",
  "Paphos, Cyprus",
  "Corfu, Greece",
  "Zakynthos, Greece",
  "Heraklion, Greece",
  "Chania, Greece",
  "Thessaloniki, Greece",
  "Sofia, Bulgaria",
  "Plovdiv, Bulgaria",
  "Varna, Bulgaria",
  "Bucharest, Romania",
  "Cluj-Napoca, Romania",
  "Brasov, Romania",
  "Belgrade, Serbia",
  "Sarajevo, Bosnia and Herzegovina",
  "Mostar, Bosnia and Herzegovina",
  "Ljubljana, Slovenia",
  "Bled, Slovenia",
  "Zagreb, Croatia",
  "Zadar, Croatia",
  "Skopje, North Macedonia",
  "Ohrid, North Macedonia",
  "Tirana, Albania",
  "Saranda, Albania",
  "Podgorica, Montenegro",
  "Kotor, Montenegro",
  "Budva, Montenegro",
  "Tallinn, Estonia",
  "Riga, Latvia",
  "Vilnius, Lithuania",
  "Kiev, Ukraine",
  "Lviv, Ukraine",
  "Odessa, Ukraine",
  "Batumi, Georgia",
  "Kutaisi, Georgia",
  "Fukuoka, Japan",
  "Nagoya, Japan",
  "Sapporo, Japan",
  "Hiroshima, Japan",
  "Sendai, Japan",
  "Kanazawa, Japan",
  "Takayama, Japan",
  "Nara, Japan",
  "Kobe, Japan",
  "Yokohama, Japan",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Jeju City, South Korea",
  "Kaohsiung, Taiwan",
  "Taichung, Taiwan",
  "Tainan, Taiwan",
  "Hualien, Taiwan",
  "Macau",
  "Da Nang, Vietnam",
  "Nha Trang, Vietnam",
  "Phu Quoc, Vietnam",
  "Vientiane, Laos",
  "Phnom Penh, Cambodia",
  "Yangon, Myanmar",
  "Bagan, Myanmar",
  "Mandalay, Myanmar",
  "Galle, Sri Lanka",
  "Bentota, Sri Lanka",
  "Hikkaduwa, Sri Lanka",
  "Mirissa, Sri Lanka",
  "Arugam Bay, Sri Lanka",
  "Austin, USA",
  "Portland, USA",
  "Denver, USA",
  "Salt Lake City, USA",
  "Phoenix, USA",
  "San Diego, USA",
  "Philadelphia, USA",
  "Boston, USA",
  "Washington D.C., USA",
  "Atlanta, USA",
  "Nashville, USA",
  "Memphis, USA",
  "Dallas, USA",
  "Houston, USA",
  "San Antonio, USA",
  "Cabo San Lucas, Mexico",
  "Puerto Vallarta, Mexico",
  "Tulum, Mexico",
  "Cozumel, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Puebla, Mexico",
  "Oaxaca, Mexico",
  "Merida, Mexico",
  "San Miguel de Allende, Mexico",
  "Orlando, USA",
  "Tampa, USA",
  "St. John's, Canada",
  "Pune, India",
  "Karachi, Pakistan",
  "Mecca, Saudi Arabia",
  "Medina, Saudi Arabia",
  "Calgary, Canada",
  "Tarpon Springs, USA",
  "Savannah, USA",
  "Charleston, USA",
  "Minneapolis, USA",
  "Detroit, USA",
  "St. Louis, USA",
  "Milwaukee, USA",
  "Indianapolis, USA",
  "Columbus, USA",
  "Charlotte, USA",
  "Raleigh, USA",
  "Richmond, USA",
  "Baltimore, USA",
  "Pittsburgh, USA",
  "Buffalo, USA",
  "Hartford, USA",
  "Providence, USA",
  "Burlington, USA",
  "Portland, ME, USA",
  "Ghent, Belgium",
  "Dinant, Belgium",
  "Utrecht, Netherlands",
  "Haarlem, Netherlands",
  "Delft, Netherlands",
  "Leiden, Netherlands",
  "Eindhoven, Netherlands",
  "Maastricht, Netherlands",
  "Groningen, Netherlands",
  "Cork, Ireland",
  "Galway, Ireland",
  "Limerick, Ireland",
  "Kilkenny, Ireland",
  "Killarney, Ireland",
  "Aberdeen, UK",
  "Inverness, UK",
  "Dundee, UK",
  "Stirling, UK",
  "Cardiff, UK",
  "Swansea, UK",
  "Newport, UK",
  "Da Lat, Vietnam",
  "Sapa, Vietnam",
  "Hue, Vietnam",
  "Mui Ne, Vietnam",
  "Can Tho, Vietnam",
  "Ha Long Bay, Vietnam",
  "Ninh Binh, Vietnam",
  "Krabi, Thailand",
  "Pattaya, Thailand",
  "Hua Hin, Thailand",
  "Koh Phangan, Thailand",
  "Koh Tao, Thailand",
  "Koh Lipe, Thailand",
  "Koh Lanta, Thailand",
  "Pai, Thailand",
  "Kanchanaburi, Thailand",
  "Ayutthaya, Thailand",
  "Sukhothai, Thailand",
  "Wellington, New Zealand",
  "Rotorua, New Zealand",
  "Napier, New Zealand",
  "Nelson, New Zealand",
  "Dunedin, New Zealand",
  "Wanaka, New Zealand",
  "Taupo, New Zealand",
  "Kaikoura, New Zealand",
  "Milford Sound, New Zealand",
  "Arusha, Tanzania",
  "Dar es Salaam, Tanzania",
  "Maun, Botswana",
  "Walvis Bay, Namibia",
  "Tangier, Morocco",
  "Agadir, Morocco",
  "Lagos, Nigeria",
  "Addis Ababa, Ethiopia",
  "Dakar, Senegal",
  "Accra, Ghana",
  "Delhi, India",
  "Bangalore, India",
  "Chennai, India",
  "Kolkata, India",
  "Udaipur, India",
  "Kochi, India",
  "Hyderabad, India",
  "Ahmedabad, India",
  "Amritsar, India",
  "Rishikesh, India",
  "Shimla, India",
  "Makhachkala, Russia",
  "Derbent, Russia",
  "Gothenburg, Sweden",
  "Malmö, Sweden",
  "Uppsala, Sweden",
  "Bergen, Norway",
  "Trondheim, Norway",
  "Tromsø, Norway",
  "Aarhus, Denmark",
  "Odense, Denmark",
  "Nuuk, Greenland",
  "Ilulissat, Greenland",
  "Sitka, USA",
  "Cappadocia, Turkey",
  "Pamukkale, Turkey",
  "Harbin, China",
  "Bishkek, Kyrgyzstan",
  "Dushanbe, Tajikistan",
  "Ashgabat, Turkmenistan",
  "Tehran, Iran",
  "Isfahan, Iran",
  "Shiraz, Iran",
  "Sharjah, UAE",
  "Ras Al Khaimah, UAE",
  "Fujairah, UAE",
  "Dhaka, Bangladesh",
  "Chittagong, Bangladesh",
  "Thimphu, Bhutan",
  "Paro, Bhutan",
  "Islamabad, Pakistan",
  "Lahore, Pakistan",
  "Faisalabad, Pakistan",
  "Multan, Pakistan",
  "Quetta, Pakistan",
  "Peshawar, Pakistan",
  "Bandar Seri Begawan, Brunei",
  "Jakarta, Indonesia",
  "Surabaya, Indonesia",
  "Bandung, Indonesia",
  "Medan, Indonesia",
  "Yogyakarta, Indonesia",
  "Semarang, Indonesia",
  "Makassar, Indonesia",
  "Palembang, Indonesia",
  "Denpasar, Indonesia",
  "Manila, Philippines",
  "Davao City, Philippines",
  "Zamboanga City, Philippines",
  "Iloilo City, Philippines",
  "Bacolod, Philippines",
  "Cagayan de Oro, Philippines",
  "General Santos, Philippines",
  "Baguio, Philippines",
  "Tagaytay, Philippines",
  "Puerto Princesa, Philippines",
  "Vigan, Philippines",
  "Legazpi, Philippines",
  "Gaza",
  "St. Petersburg, Russia",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Cologne, Germany",
  "Bratislava, Slovakia",
  "San Jose, USA",
  "Jacksonville, USA",
  "Fort Worth, USA",
  "El Paso, USA",
  "Oklahoma City, USA",
  "Albuquerque, USA",
  "Tucson, USA",
  "Sacramento, USA",
  "Kansas City, USA",
  "Mesa, USA",
  "Virginia Beach, USA",
  "Omaha, USA",
  "Cleveland, USA",
  "Tulsa, USA",
  "Wichita, USA",
  "Bakersfield, USA",
  "Aurora, USA",
  "Anaheim, USA",
  "Santa Ana, USA",
  "Riverside, USA",
  "Corpus Christi, USA",
  "Lexington, USA",
  "Stockton, USA",
  "Cincinnati, USA",
  "St. Paul, USA",
  "Greensboro, USA",
  "Toledo, USA",
  "Newark, USA",
  "Plano, USA",
  "Henderson, USA",
  "Lincoln, USA",
  "Jersey City, USA",
  "Fort Wayne, USA",
  "Chandler, USA",
  "St. Petersburg, USA",
  "Laredo, USA",
  "Durham, USA",
  "Irvine, USA",
  "Madison, USA",
  "Norfolk, USA",
  "Lubbock, USA",
  "Gilbert, USA",
  "Winston-Salem, USA",
  "Glendale, USA",
  "Reno, USA",
  "Hialeah, USA",
  "Chesapeake, USA",
  "Garland, USA",
  "Irving, USA",
  "Scottsdale, USA",
  "North Las Vegas, USA",
  "Fremont, USA",
  "Baton Rouge, USA",
  "Boise, USA",
  "San Bernardino, USA",
  "Algiers, Algeria",
  "Luanda, Angola",
  "Caracas, Venezuela",
  "Montevideo, Uruguay",
  "Asuncion, Paraguay",
  "La Paz, Bolivia",
  "Santa Cruz, Bolivia",
  "Guayaquil, Ecuador",
  "Belo Horizonte, Brazil",
  "Curitiba, Brazil",
  "Recife, Brazil",
  "Porto Alegre, Brazil",
  "Cordoba, Argentina",
  "Rosario, Argentina",
  "Mendoza, Argentina",
  "Valparaiso, Chile",
  "Arequipa, Peru",
  "Trujillo, Peru",
  "Cali, Colombia",
  "Barranquilla, Colombia",
  "Bucaramanga, Colombia",
  "Maracaibo, Venezuela",
  "Valencia, Venezuela",
  "Georgetown, Guyana",
  "Paramaribo, Suriname",
  "Cayenne, French Guiana",
  "Abidjan, Ivory Coast",
  "Kinshasa, DR Congo",
  "Kampala, Uganda",
  "Kigali, Rwanda",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
  "Maputo, Mozambique",
  "Gaborone, Botswana",
  "Maseru, Lesotho",
  "Mbabane, Eswatini",
  "Bujumbura, Burundi",
  "Djibouti City, Djibouti",
  "Asmara, Eritrea",
  "Bologna, Italy",
  "Palermo, Italy",
  "Bilbao, Spain",
  "Malaga, Spain",
  "Alicante, Spain",
  "Coimbra, Portugal",
  "Funchal, Madeira, Portugal",
  "Winnipeg, Canada",
  "Halifax, Canada",
  "Kelowna, Canada",
  "Nagasaki, Japan",
  "Kumamoto, Japan",
  "Gwangju, South Korea",
  "Daegu, South Korea",
  "Ulsan, South Korea"
];

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

export const ACTIVITIES = [
  "General",
  "Beach & Swimming",
  "Hiking & Nature",
  "Sightseeing & Museums",
  "Food & Nightlife",
  "Skiing & Winter Sports"
];
